export const cartas = [
  {
    nome: "Liliana do Veu",
    custo_mana: "5UU",
    atributos: ["Voar", "Lifelink"],
    descricao: "Carta roubada",
    ataque: 5,
    resistencia: 2,
  },
  {
    nome: "Baram da Morte",
    custo_mana: "UUU",
    atributos: ["Toque Mortifero", "Lifelink"],
    descricao: "Mestre Zumbi",
    ataque: 3,
    resistencia: 3,
  },
  {
    nome: "Mestre zumbi",
    custo_mana: "1U",
    atributos: ["Imortal"],
    descricao: "Zumbizão",
    ataque: 2,
    resistencia: 3,
  },
  {
    nome: "Garruk, o Imortal",
    custo_mana: "3GGG",
    atributos: ["Atropelar", "+1/+1"],
    descricao: "Caçador voraz",
    ataque: 5,
    resistencia: 5,
  },
  {
    nome: "Jace, o Viadinho Azul",
    custo_mana: "1A",
    atributos: ["Compra Carta", "Descarta Carta"],
    descricao: "É um viadinho supremo",
    ataque: 1,
    resistencia: 1,
  },
  {
    nome: "Chandra, Fogosa",
    custo_mana: "2RR",
    atributos: ["1 de dano no começo do turno"],
    descricao: "Sempre te dando dano",
    ataque: 3,
    resistencia: 2,
  },
  {
    nome: "Fera Dorço de couro",
    custo_mana: "GGG",
    atributos: ["Atropelar", "Resistencia a magia"],
    descricao: "Uma besta sem controle",
    ataque: 6,
    resistencia: 4,
  },
  {
    nome: "Pequeno Goblim",
    custo_mana: "1R",
    atributos: ["Nada"],
    descricao: "Pequeno e medroso",
    ataque: 1,
    resistencia: 1,
  },
  {
    nome: "Dragão, Vermelho",
    custo_mana: "4R",
    atributos: ["Voar", "Travesia de Montanha"],
    descricao: "Dragão, Vermelho é um asdo caçador dos ceús",
    ataque: 5,
    resistencia: 6,
  },
  {
    nome: "Nicol, Bolas Supremo",
    custo_mana: "RGBWU",
    atributos: ["indestrutivel", "Voar", "Atropelar"],
    descricao: "O mago dragão supremo está sem controle",
    ataque: 10,
    resistencia: 10,
  },
  {
    nome: "Tritão Baitola",
    custo_mana: "2BB",
    atributos: ["Compra uma carta"],
    descricao: "É um tritão afim do Jace, Viadinho",
    ataque: 2,
    resistencia: 2,
  },
  {
    nome: "Esquilo Voador",
    custo_mana: "2GG",
    atributos: ["Voar", "Imbloqueavel"],
    descricao: "Esquilo Voador esta sempre roubando suas nozes",
    ataque: 3,
    resistencia: 1,
  },
  {
    nome: "Hidra Caloniana",
    custo_mana: "XGG",
    atributos: ["Dobra de marcador a cada turno", "Atropelar"],
    descricao: "Uma fera quase imparavel",
    ataque: 0,
    resistencia: 1,
  },
  {
    nome: "Anjo Divino",
    custo_mana: "6WWW",
    atributos: ["Voar", "Proteção contra preto", "Lifelink"],
    descricao: "Anjo Divino está aqui para te salvar",
    ataque: 8,
    resistencia: 7,
  },
  {
    nome: "Demonio, Torturador de todos",
    custo_mana: "6B",
    atributos: ["Lifelink", "Voar", "Toque Mortifero"],
    descricao: "Ele esta aqui para torturar a todos sem misericordia",
    ataque: 8,
    resistencia: 8,
  },
];
